
package prewitdetection;

import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;


public class PrewittDetection extends javax.swing.JFrame {
BufferedImage   Prewit;        
    int lebarGbr, tinggiGbr;    
    String warna;              
    int wMerah,wHijau,wBiru;    
    private JLabel gambar;
    private JLabel gambar1;

    public PrewittDetection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Click = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btn_Click.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Click.setForeground(new java.awt.Color(255, 0, 0));
        btn_Click.setText("Operator Sobel");
        btn_Click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Click)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Click)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClickActionPerformed
        setLayout(new FlowLayout());
        
        try {
            File masukan = new File("D:\\img.jPg");
            Prewit = ImageIO.read(masukan);
            ImageIcon imageicon1 = new ImageIcon(Prewit);
            gambar = new JLabel(imageicon1);
            lebarGbr = Prewit.getWidth();
            tinggiGbr = Prewit.getHeight();
               int x = Prewit.getWidth();
        int y = Prewit.getHeight();
        
        int maxGval = 0;
        int [][] edgeColors = new int [x][y];
        int maxGradient = -1;
        
        for (int i = 1; i < x - 1; i++) {
            for (int j = 1; j < y - 1; j++) {
                 
                int val00 = getGrayScale(Prewit.getRGB(i - 1, j - 1));
                int val01 = getGrayScale(Prewit.getRGB(i - 1, j    ));
                int val02 = getGrayScale(Prewit.getRGB(i - 1, j + 1));
                
                int val10 = getGrayScale(Prewit.getRGB(i, j - 1));
                int val11 = getGrayScale(Prewit.getRGB(i, j)    );
                int val12 = getGrayScale(Prewit.getRGB(i, j + 1));
                
                int val20 = getGrayScale(Prewit.getRGB(i + 1, j - 1));
                int val21 = getGrayScale(Prewit.getRGB(i + 1, j)    );
                int val22 = getGrayScale(Prewit.getRGB(i + 1, j + 1));
                
                int gx = ((-1 * val00) + (0 * val01) + (1 * val02))
                       + ((-1 * val10) + (0 * val11) + (1 * val12))
                       + ((-1 * val20) + (0 * val21) + (1 * val22));
                
                int gy = ((-1 * val00) + (-1* val01) + (-1* val02))
                       + ((0  * val10) + (0 * val11) + (0 * val12))
                       + ((1  * val20) + (0 * val21) + (1 * val22));
                
                double gval = Math.sqrt((gx * gx) + (gy * gy));
                int g = (int) gval;
                
                if(maxGradient < g) {
                    maxGradient = g;
                }
                edgeColors[i][j] = g;
            }
        }
        
            double scale = 255.0 / maxGradient;

            for (int i = 1; i < x - 1; i++) {
                for (int j = 1; j < y - 1; j++) {
                    int edgeColor = edgeColors[i][j];
                    edgeColor = (int) (edgeColor * scale);
                    edgeColor = 0xff000000 | (edgeColor << 16) | (edgeColor << 8) | edgeColor;

                    Prewit.setRGB(i, j, edgeColor );

                }
            }
               
            ImageIcon imageicon = new ImageIcon(Prewit);
            gambar1 = new JLabel(imageicon);
            
            add(gambar1);
            add(gambar);
            setVisible(true);
            setSize(650,400);
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        } catch (IOException entok) { }
    }//GEN-LAST:event_btn_ClickActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    public static int getGrayScale(int rgb) {
        int r = (rgb >> 16) & 0xff;
        int g = (rgb >>  8) & 0xff;
        int b = (rgb)       & 0xff;
        
        //from https://en.wikipedia.org/wiki/Grayslae.calculating luminance
        int gray = (int) (0.2126 * r + 0.7152 * g + 0.0722 * b);
        // int gray = (r+g+b)/3
        
        return gray;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrewittDetection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrewittDetection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrewittDetection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrewittDetection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrewittDetection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Click;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
